vscode:
  extensions:
    - rust-lang.rust@0.6.3:HqKSYOrvQWB/7AqVWuok/A==

image:
  file: .gitpod.dockerfile

tasks:
  - init: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y && cargo install diesel_cli --no-default-features --features postgres && psql -f init.sql && diesel setup --database-url="postgres://dnd_agenda:dnd_agenda@localhost/dnd_agenda" && diesel migration run --database-url="postgres://dnd_agenda:dnd_agenda@localhost/dnd_agenda"
