vscode:
  extensions:
    - rust-lang.rust@0.6.3:HqKSYOrvQWB/7AqVWuok/A==

image:
  file: .gitpod.dockerfile

tasks:
  - init: diesel setup --database-url="postgres://dnd_agenda:dnd_agenda@localhost/dnd_agenda" && diesel migration run --database-url="postgres://dnd_agenda:dnd_agenda@localhost/dnd_agenda"