-- Your SQL goes here
CREATE TABLE sessions_guests (
    session_id INT NOT NULL REFERENCES sessions (id) ON UPDATE CASCADE ON DELETE CASCADE,
    guest_id INT GENERATED BY DEFAULT AS IDENTITY,
    guest_name TEXT NOT NULL UNIQUE,
    CONSTRAINT sessions_guests_pkey PRIMARY KEY (session_id, guest_id)
)