-- Your SQL goes here
CREATE TABLE sessions_users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id INT NOT NULL REFERENCES sessions (id) ON UPDATE CASCADE ON DELETE CASCADE,
    user_id INT NOT NULL REFERENCES users (id) ON UPDATE CASCADE,
    dm_accepted BOOLEAN NOT NULL DEFAULT FALSE,
    user_accepted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT sessions_users_pkey PRIMARY KEY (session_id, user_id)
)