-- Your SQL goes here
CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    bio TEXT,
    image TEXT DEFAULT 'https://dndearall.com/img/smiley.jpg',
    password TEXT NOT NULL
)