-- Your SQL goes here
CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    bio TEXT,
    image TEXT DEFAULT 'https://i.ibb.co/F7gn5W9/smiley.jpg',
    password TEXT NOT NULL
)